name: Playwright + Allure

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser(s) to execute Playwright tests"
        type: choice
        required: true
        default: chromium
        options: [all, chromium, firefox, webkit]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-jammy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean old artifacts (IMPORTANT)
        run: |
          rm -rf github-pages
          rm -rf allure-results
          rm -rf allure-report
          rm -rf allure-history

      - name: Setup Node cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests (ALL browsers in parallel)
        if: ${{ inputs.browser == 'all' }}
        run: npx playwright test --retries=2

      - name: Run tests (single browser)
        if: ${{ inputs.browser != 'all' }}
        run: npx playwright test --project=${{ inputs.browser }} --retries=2

      - name: Install Java
        if: always()
        run: |
          apt-get update -y
          apt-get install -y openjdk-17-jre

      - name: Generate Allure Report
        if: always()
        run: |
          rm -rf allure-report
          rm -rf allure-results/history
          npx allure generate allure-results --clean -o allure-report

      - name: Upload Pages artifact (Allure)
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: allure-report

  deploy-pages:
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
